name=ModbusMasterRTU
version=1.0.2
author=Marcin Bania
maintainer=Marcin Bania
sentence=Library for connect MCU to Modbus RS485 RTU in master mode
paragraph=Library for connect MCU to Modbus RS485 RTU in master mode
category=Communication
url=https://github.com/anarhbania/Supla/libraries/ModbusMasterRTU
architectures=avr,stm32,esp8266,esp32
includes=ModbusMasterRTU.h
