name=ModbusMaster
version=1.0.0
author=Marcin Bania
maintainer=Marcin Bania
sentence=Library for connect MCU to Modbus RS485 RTU in master mode
paragraph=Library for connect MCU to Modbus RS485 RTU in master mode
category=Communication
url=https://github.com/anarhbania/Supla/libraries/ModbusMaster
architectures=avr,stm32,esp8266,esp32
includes=ModbusMaster.h
